-- code generated by funky's haskell generator
-- timestamp: 2019-02-25 at 15:46:18

-- section: create_adts
v2 = \v2_0 -> \v2_1 -> \v2_2 -> ((v2_0)(v2_2))(v2_1)
v0 = True
v5 = \v5_0 -> case ((>=)(v5_0))(0) of { True -> v5_0; False -> case v0 of { True -> (negate)(v5_0); False -> undefined } }
v15 = 2
v14 = v15
v13 = ((v2)(**))(0.5)

-- section: emit_main
main = do
       print ((v13)((v5)(v14)))
