import datetime

def annotate_section(f):
    """Use this decorator on a function if you want to emit an annotation
    detailing the start of a section in the source code. For example, if you
    apply this decorator to a function `header`, the code generator will
    print 'section: header' as a comment before any emitted code from that
    section.
    """
    def wrapper(*args, **kwargs):
        self = args[0]
        com = self.comment("section: {}".format(f.__name__))
        self.emit(com)
        f(*args, **kwargs)
    return wrapper

class CodeGenerator:
    """A code generator. Maintains an internal 'program' buffer that will
    contain the source of the target language. Provides helper functions to
    'emit' code to this buffer. Code generators targeting a specific language
    should inherit from this base class.
    """

    def __init__(self, lang_name):
        self.lang_name = lang_name
        self.reset()

    def reset(self):
        """Resets the state of the code generator so it can be used again."""
        self.program = ""

    def code_header(self):
        self.emit(self.comment("code generated by funky's {} "
                               "generator".format(self.lang_name.lower())))
        self.emit(self.comment("timestamp: {}".format(self.timestamp())))
        self.newline()

    def emit(self, s, d=0):
        """Emit a string to the program buffer.
        
        :param s str: the string to emit
        :param d int: how many spaces of indentation to apply (default: 0)
        """
        self.program += "{}{}\n".format(" " * d, s)

    def newline(self):
        """Emit a newline to the program buffer."""
        self.emit("")

    def timestamp(self):
        """Get the current time as a string. This can then be emitted to the
        generated code to 'timestamp' compiler artifacts.
        """
        return datetime.datetime.today().strftime('%Y-%m-%d at %H:%M:%S')

    def do_generate_code(self, core_tree, typedefs):
        """Generate code for this target.
        
        :param core_tree CoreNode:            the core tree to compile
        :param typedefs [CoreTypeDefinition]: a list of type definitions
        """
        raise NotImplementedError("Code generation not defined for this target.")
