#!/usr/bin/env bash
PARENT_PATH=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
cd "$PARENT_PATH"

if [ ! $(command -v funky) > /dev/null ]; then
    echo "funky is not installed, cannot compile samples"
    exit 1
fi

COMPILED_DIR=compiled
FKY_FILES=$(find . -name 'sample_*.fky')

mkdir -p $COMPILED_DIR
for source_file in $FKY_FILES; do
    output_file=$(basename $source_file .fky)
    echo "Now compiling $source_file..."
    funky -o $COMPILED_DIR/$output_file.py --target=python $source_file $@
    funky -o $COMPILED_DIR/$output_file.hs --target=haskell $source_file $@
done
